<span style="color:RED;font-weight:700;font-size:55px">
TENSORFLOW BASICS
</span>

In [2]:
import tensorflow as tf

AttributeError: module 'tensorflow.python.framework.dtypes' has no attribute 'float8_e4m3fn'

### __ZERO DIMENSIONAL TENSOR__

In [ ]:
tensor_zero_d = tf.constant(4) #zero dim tensor
tensor_zero_d

### __ONE DIMENSIONAL TENSOR__

In [ ]:
tensor_one_d = tf.constant([2,0,-3], dtype=tf.float32) #one dim tensor
tensor_one_d

### __TWO DIMENSIONAL TENSOR__

In [ ]:
tensor_two_d = tf.constant([
    [2,0,-3],
    [3,5,1],                     #two dim tensor
    [-9,6,7]
    ]) 
tensor_two_d

### __THREE DIMENSIONAL TENSOR__

In [ ]:
tensor_three_d = tf.constant([

    [
        [2,5,1],[6,7,9]
    ],
    [
        [-9,2,-7],[8,2,6]            #three dim tensor
    ],
    [
        [6,5,2],[-1,0,3]
    ]
])
tensor_three_d

### __FOUR DIMMENSIONAL TENSOR__

In [ ]:
tensor_four_d = tf.constant([                #four dim tensor
     [[
        [2,5,1],[6,7,9]
    ],
    [
        [-9,2,-7],[8,2,6]            #three dim tensor
    ],
    [
        [6,5,2],[-1,0,3]
    ]],
    [[
        [2,8,1],[-6,7,9]
    ],
    [
        [-2,1,-7],[5,2,6]            #three dim tensor
    ],
    [
        [1,5,3],[-1,8,3]
    ]]
])
tensor_four_d

### __SHAPE__

In [ ]:
print(tensor_zero_d.shape)
print(tensor_one_d.shape)
print(tensor_two_d.shape)
print(tensor_three_d.shape)
print(tensor_four_d.shape)

### __NDIM OF TENSOR__

In [ ]:
print(tensor_zero_d.ndim)
print(tensor_one_d.ndim)
print(tensor_two_d.ndim)
print(tensor_three_d.ndim)
print(tensor_four_d.ndim)

### __TYPE CASTING__ 

In [ ]:
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int64)
casted_tensor_one_d

### __NUMPY TO TENSOR__

In [4]:
import numpy as np

In [ ]:
np_arr = np.array([1,5,9])
print(np_arr)

converted_tensor = tf.convert_to_tensor(np_arr)
print(converted_tensor)

### __EYE TENSOR__

In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.bool,
    name=None
)
eye_tensor

### __FILL TENSOR__

In [ ]:
fill_tensor = tf.fill([2,3,3],3)
fill_tensor

### __ONE'S TENSOR__

In [ ]:
ones_tensor = tf.ones(
    [3,2,1],
    dtype=tf.dtypes.float32,
    name=None
)
ones_tensor

### __ONE'S LIKE TENSOR__

In [ ]:
np_arr=np.array([[2,1,7],[-5,-1,0]])
ones_like_tensor = tf.ones_like(
    np_arr
)
ones_like_tensor

### __ZERO'S TENSOR__

In [ ]:
zeros_tensor = tf.zeros(
    [3,2,1],
    dtype=tf.dtypes.int32,
    name=None
)
zeros_tensor

### __ZERO'S LIKE TENSOR__

In [ ]:
np_arr=np.array([[2,1,7],[-5,-1,0]])
zeros_like_tensor = tf.zeros_like(
    np_arr
)
zeros_like_tensor

### __RANK__

In [ ]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
#shape of t is [2,2,3] same like ndim it returns the dimension alone
tf.rank(t)

### __SIZE__

In [27]:
t = tf.constant([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
tf.size(t,out_type=tf.dtypes.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

### __RANDOM NORMAL__

In [ ]:
random_tensor = tf.random.normal(
    [2,2],
    mean=100.0,
    stddev=5.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
random_tensor

### __RANDOM UNIFORM__

In [ ]:
uniform_tensor = tf.random.uniform(
    [2,2],
    minval=0,
    maxval=8,
    dtype=tf.dtypes.int64,
    seed=None,
    name=None
)
uniform_tensor

### __ABS__

In [ ]:
t = tf.constant([-2.13,-3.69,9.32])
tf.abs(t)

### __DIVIDE__

In [ ]:
x1 = tf.constant([2,3,4,5,6],dtype=tf.float32)
x2 = tf.constant([2,0,4,0,7],dtype=tf.float32) 
tf.math.divide(x1,x2)

### __DIVIDE NO NAN__

In [ ]:
x1 = tf.constant([2,3,4,5,6],dtype=tf.float32)
x2 = tf.constant([2,0,4,0,7],dtype=tf.float32) 
tf.math.divide_no_nan(x1,x2)

### __ADD__

In [ ]:
x1 = tf.constant([[2,3,4,5,6],[1,2,4,5,0]],dtype=tf.float32)
x2 = tf.constant([7],dtype=tf.float32)
x2_stretched = tf.constant([7,7,7,7,7],dtype=tf.float32)

print(tf.add(x1,x2))
print(tf.add(x1,x2_stretched))

### __SUBTRACT__

In [ ]:
x1 = tf.constant([[2,3,4,5,6],[1,2,4,5,0]],dtype=tf.float32)
x2 = tf.constant([7],dtype=tf.float32)
x2_stretched = tf.constant([7,7,7,7,7],dtype=tf.float32)

print(tf.subtract(x1,x2))
print(tf.subtract(x1,x2_stretched))

### __MULTIPLY__

In [ ]:
x1 = tf.constant([[2,3,4,5,8,9]],dtype=tf.int32)
x2 = tf.constant([[7],[5],[3]],dtype=tf.int32)


print(tf.multiply(x1,x2))

### __ARGMAX__

In [ ]:
x1 = tf.constant([
    [2,0,-3],
    [3,5,1],                     
    [-9,6,7]
    ])
print(tf.argmax(x1,axis=0))

x2 = tf.constant([2,3,4,55,8,9])
print(tf.argmax(x2))

### __ARGMIN__

In [ ]:
x1 = tf.constant([
    [2,10,-3],
    [3,5,1],                     
    [-9,6,7]
    ])
print(tf.argmin(x1,axis=1))

x2 = tf.constant([2,3,4,55,1,9])
print(tf.argmin(x2))

### __POW__

In [ ]:
x1 = tf.constant([[2,3],[1,8]])
x2 = tf.constant([x1[2,1],[4,2]])
tf.pow(x1,x2)

### __REDUCE__

In [ ]:
t = tf.constant([
    [2,10,-3],
    [3,5,1],                     
    [-9,6,7]
    ])

print(tf.reduce_sum(t,axis=0,keepdims=[1,3],name=None))
print(tf.reduce_max(t))
print(tf.reduce_min(t))
print(tf.reduce_prod(t))
print(tf.reduce_mean(t))

### __EXPAND DIMS__

In [1]:
t = tf.constant([
    [2,10,-3],
    [3,5,1],                     
    [-9,6,7]
    ])

print(t.shape)
print(tf.expand_dims(t,axis=0).shape)

NameError: name 'tf' is not defined

### __SQUEEZE__

In [17]:
t = tf.constant([

    [
        [2,5,1],[6,7,9]
    ],
    [
        [-9,2,-7],[8,2,6]            
    ],
    [
        [6,5,2],[-1,0,3]
    ]
])
print(t.shape)
expand = tf.expand_dims(t,axis=0)
print(expand.shape)
squeeze = tf.squeeze(expand,axis=0)
print(squeeze)

(3, 2, 3)
(1, 3, 2, 3)
tf.Tensor(
[[[ 2  5  1]
  [ 6  7  9]]

 [[-9  2 -7]
  [ 8  2  6]]

 [[ 6  5  2]
  [-1  0  3]]], shape=(3, 2, 3), dtype=int32)


### __RESHAPE__

In [23]:
t = tf.constant([
    [2,10,-3],
    [3,5,1],                     
    [-9,6,7]
    ])

print(tf.reshape(t,[9]))
print(tf.reshape(t,[3,1,3]))

tf.Tensor([ 2 10 -3  3  5  1 -9  6  7], shape=(9,), dtype=int32)
tf.Tensor(
[[[ 2 10 -3]]

 [[ 3  5  1]]

 [[-9  6  7]]], shape=(3, 1, 3), dtype=int32)


### __CONCAT__

In [26]:
x1 = np.array([[2,3],
                  [1,8]])
x2 = np.array([[2,1],
                  [4,2]])

print(tf.concat([x1,x2], axis=0))
print(tf.concat([x1,x2], axis=1))

tf.Tensor(
[[2 3]
 [1 8]
 [2 1]
 [4 2]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[2 3 2 1]
 [1 8 4 2]], shape=(2, 4), dtype=int32)


### __NP EINSUM__

In [5]:
x1 = np.array([[2,3],
                  [1,8]])
x2 = np.array([[2,1],
                  [4,2]])

print("MATRICS MULTIPLICATION USING MATMUL :\n")
print(np.matmul(x1,x2),"\n")

print("MATRICS MULTIPLICATION USING EINSUM :\n")
print(np.einsum('ij,jk -> ik',x1,x2),"\n")

print("ELEMENT WISE MULTIPLICATION USING HARDAMOND :\n")
print(x1*x2,"\n")

print("ELEMENT WISE MULTIPLICATION USING EINSUM :\n")
print(np.einsum('ij,ij -> ij',x1,x2),"\n")

MATRICS MULTIPLICATION USING MATMUL :

[[16  8]
 [34 17]] 

MATRICS MULTIPLICATION USING EINSUM :

[[16  8]
 [34 17]] 

ELEMENT WISE MULTIPLICATION USING HARDAMOND :

[[ 4  3]
 [ 4 16]] 

ELEMENT WISE MULTIPLICATION USING EINSUM :

[[ 4  3]
 [ 4 16]] 



### __NP TRANSPOSE__

In [6]:
A = np.array([[2,3],
                  [1,8]])

print("TRANSPOSE USING NUMPY :\n")
print(A.T,"\n")

print("TRANSPOSE USING EINSUM :\n")
print(np.einsum('ij->ji',A))

TRANSPOSE USING NUMPY:

[[2 1]
 [3 8]] 

TRANSPOSE USING EINSUM :

[[2 1]
 [3 8]]


### __SPARSE__

In [28]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1],[3,4]],values =[33,99], dense_shape=[5,6]
)
print(tensor_sparse)

tf.sparse.to_dense(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([33 99], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 33,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 99,  0],
       [ 0,  0,  0,  0,  0,  0]])>

### __STRINGS__

In [33]:
tensor_string = tf.constant(['hello','i am','string'])
print(tensor_string)

print(tf.strings.join(tensor_string,separator=' '))
print(tf.strings.length(tensor_string))
print(tf.strings.upper(tensor_string))

tf.Tensor([b'hello' b'i am' b'string'], shape=(3,), dtype=string)
tf.Tensor(b'hello i am string', shape=(), dtype=string)
tf.Tensor([5 4 6], shape=(3,), dtype=int32)
tf.Tensor([b'HELLO' b'I AM' b'STRING'], shape=(3,), dtype=string)


#### __STACK__

In [10]:
x1 = np.array([[2,3],
                  [1,8]])
x2 = np.array([[2,1],
                  [4,2]])

tf.stack([x1,x2,x1,x2],axis=1)

<tf.Tensor: shape=(2, 4, 2), dtype=int32, numpy=
array([[[2, 3],
        [2, 1],
        [2, 3],
        [2, 1]],

       [[1, 8],
        [4, 2],
        [1, 8],
        [4, 2]]])>

### __VARIABLE__

In [12]:
x= tf.constant([1,2])
x_var = tf.Variable(x,name='var1')
x_var

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

### __VARIABLE ASSIGN__

In [20]:
var = tf.Variable(1)
var.assign(2)
print(var)

var.assign_add(3)
print(var)
var.assign_sub(3)
print(var)
x_var.assign_add([3,3])
print(x_var,end="\n")

with tf.device('CPU:0'):
    x_1 = tf.constant([1,2])
    x_2 = tf.constant([3,4])


with tf.device('GPU:0'):
    x_3 = x_1 + x_2

print(x_1 , x_1.device)
print(x_2 , x_2.device)
print(x_3 , x_3.device)
    

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>
<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([16, 17])>
tf.Tensor([1 2], shape=(2,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([3 4], shape=(2,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([4 6], shape=(2,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
