<span style="color:RED;font-weight:700;font-size:45px">
TENSORFLOW LINALG BASICS
</span>

In [3]:
import tensorflow as tf

### __MATMUL__

In [9]:
x1 = tf.constant([[2,3],
                  [1,8]])
x2 = tf.constant([[2,1],
                  [4,2]])

print(tf.linalg.matmul(
    x1,x2,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False
))
print(x1@x2) #matmul
print(x1*x2) #elemul

tf.Tensor(
[[16  8]
 [34 17]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[16  8]
 [34 17]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 4  3]
 [ 4 16]], shape=(2, 2), dtype=int32)


### __TRANSPOSE__

In [10]:
x1 = tf.constant([[2,3],[1,8]])
tf.transpose(x1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [3, 8]])>

### __BAND PART__

In [21]:
t = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]       
])

print(tf.linalg.band_part(t,num_lower=0,num_upper=0))  #diagnol
print(tf.linalg.band_part(t,num_lower=0,num_upper=-1)) #lower triangal
print(tf.linalg.band_part(t,num_lower=-1,num_upper=0)) #upper triangle
print(tf.linalg.band_part(t,num_lower=1,num_upper=1))  #keeping diagnol

tf.Tensor(
[[1 0 0]
 [0 5 0]
 [0 0 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [0 5 6]
 [0 0 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [4 5 0]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 0]
 [4 5 6]
 [0 8 9]], shape=(3, 3), dtype=int32)


### __CROSS PRODUCT__

In [28]:
x1 = tf.constant([1.0,0.0,0.0])
x2 = tf.constant([0.0,1.0,0.0])

cross_product = tf.linalg.cross(x1,x2)
cross_product

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 1.], dtype=float32)>

### __INVERSE__

In [33]:
#A⁻¹ = (1/det(A)) * adjugate(A)

x1 = tf.constant([[4.,7.],[2.,6.]]) # 2x2

print(tf.linalg.inv(x1))

''' 
A = | 4  7 |
    | 2  6 |

det(x1) = (4*6) - (7*2) = 10

Adj(x1) = (1/10) * | 6   -7 |
                   | -2   4 |
'''
x2 = tf.constant([                #3x3
    [2.0, 1.0, 3.0],
    [1.0, 2.0, 1.0],
    [3.0, 1.0, 2.0]
])

print(tf.linalg.inv(x2))

'''
A = | 2  1  3 |
    | 1  2  1 |
    | 3  1  2 |

det(x2) = a(ei - fh) - b(di - fg) + c(dh - eg)

a = 2, b = 1, c = 3
d = 1, e = 2, f = 1
g = 3, h = 1, i = 2

det(A) = 2(2x2 - 1x1) - 1(1x2 - 1x3) + 3(1x1 - 2x3)
        = 2(4 - 1) - 1(2 - 3) + 3(1 - 6)
        = 2(3) - 1(-1) + 3(-5)
        = 6 + 1 - 15
        = -8

C₁₁ = det|2 1| = (2x2 - 1x1) = 3 → sign: + |1 2|

C₁₂ = det|1 1| = (1x2 - 1x3) = -1 → sign: - |3 2|

C₁₃ = det|1 2| = (1x1 - 2x3) = -5 → sign: + |3 1|

Cofactor Matrix =
|  3   1  -5 |
| -1   5  -1 |
|  1  -2   1 |

Transpose the Cofactor Matrix (to get Adjugate)
Adjugate =
|  3  -1   1 |
|  1   5  -2 |
| -5  -1   1 |

A⁻¹ =
|  3  -1   1 |              |  -0.375  0.125 -0.125 |
|  1   5  -2 | x  (-1/8)  = |  -0.125 -0.625  0.25  |
| -5  -1   1 |              |   0.625  0.125 -0.125 |

'''

tf.Tensor(
[[ 0.6 -0.7]
 [-0.2  0.4]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.375      -0.125       0.625     ]
 [-0.12499999  0.625      -0.12500001]
 [ 0.625      -0.12499999 -0.375     ]], shape=(3, 3), dtype=float32)


'\nA = | 2  1  3 |\n    | 1  2  1 |\n    | 3  1  2 |\n\ndet(x2) = a(ei - fh) - b(di - fg) + c(dh - eg)\n\na = 2, b = 1, c = 3\nd = 1, e = 2, f = 1\ng = 3, h = 1, i = 2\n\ndet(A) = 2(2x2 - 1x1) - 1(1x2 - 1x3) + 3(1x1 - 2x3)\n        = 2(4 - 1) - 1(2 - 3) + 3(1 - 6)\n        = 2(3) - 1(-1) + 3(-5)\n        = 6 + 1 - 15\n        = -8\n\nC₁₁ = det|2 1| = (2x2 - 1x1) = 3 → sign: + |1 2|\n\nC₁₂ = det|1 1| = (1x2 - 1x3) = -1 → sign: - |3 2|\n\nC₁₃ = det|1 2| = (1x1 - 2x3) = -5 → sign: + |3 1|\n\nCofactor Matrix =\n|  3   1  -5 |\n| -1   5  -1 |\n|  1  -2   1 |\n\nTranspose the Cofactor Matrix (to get Adjugate)\nAdjugate =\n|  3  -1   1 |\n|  1   5  -2 |\n| -5  -1   1 |\n\nA⁻¹ =\n|  3  -1   1 |              |  -0.375  0.125 -0.125 |\n|  1   5  -2 | x  (-1/8)  = |  -0.125 -0.625  0.25  |\n| -5  -1   1 |              |   0.625  0.125 -0.125 |\n\n'

### __SINGULAR VALUE DECOMPOSITION (SVD)__

In [36]:
A = tf.constant([[4.,7.],[2.,6.]])

s,u,v=tf.linalg.svd(A)

print(s,"\n",u,"\n",v)

'''
s -- singular value (sigma square)
u -- left singular vector (AAt)
v -- right singular vector (AtA)

'''

tf.Tensor([10.199942   0.9803978], shape=(2,), dtype=float32) 
 tf.Tensor(
[[ 0.7882054   0.61541224]
 [ 0.61541224 -0.7882054 ]], shape=(2, 2), dtype=float32) 
 tf.Tensor(
[[ 0.42977166  0.9029376 ]
 [ 0.9029376  -0.42977166]], shape=(2, 2), dtype=float32)


'\ns -- singular value (sigma square)\nu -- left singular vector (AAt)\nv -- right singular vector (AtA)\n'